version: '3.8'

services:
  reminder:
    container_name: reminder
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      TZ: "Europe/Moscow"
      SPRING_PROFILES_ACTIVE: docker
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_SECRET: ${GOOGLE_OAUTH_SECRET}
      GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
      GITHUB_OAUTH_SECRET: ${GITHUB_OAUTH_SECRET}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - reminder-postgres

  reminder-postgres:
    container_name: reminder-postgres
    image: postgres:17.4
    ports:
      - '5433:5432'
    environment:
      TZ: "Europe/Moscow"
      PGTZ: Europe/Moscow
      POSTGRES_DB: reminder-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - reminder-db:/var/lib/postgresql/data

volumes:
  reminder-db: