-- changeset pavel.vlezko:1
CREATE TABLE Users
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(128),
    telegram VARCHAR(128) UNIQUE
);

CREATE TABLE Reminders
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255),
    description VARCHAR(4096),
    remind      TIMESTAMP NOT NULL,
    user_id     BIGINT    NOT NULL REFERENCES Users (id) ON DELETE CASCADE
);